SoftUniAdminSystem/SUAS.Web/Areas/Administration/Controllers/RolesController.cs
namespace SUAS.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Services.Contracts;
    using Models;
    using ViewModels;

    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller
    {
        private readonly RoleManager<Role> roleManager;
        private readonly IRoleService roles;

        public RolesController(RoleManager<Role> roleManager, IRoleService roles)
        {
            this.roleManager = roleManager;
            this.roles = roles;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = this.roles.GetAllRoles().Select(r => new RoleListViewModel
            {
                RoleName = r.Name,
                Id = r.Id,
                Description = r.Description,
                NumberOfUsers = this.roles.GetCountOfUsersInRole(r)
            }).ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create(string id)
        {
            var model = new RoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                var role = this.roles.GetRoleById(id);
                if (role != null)
                {
                    model.Id = role.Id;
                    model.RoleName = role.Name;
                    model.Description = role.Description;
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string id, RoleViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var isExist = !String.IsNullOrEmpty(id);
                var role = isExist ? this.roles.GetRoleById(id) :
                    new Role
                    {
                        CreatedDate = DateTime.UtcNow
                    };

                role.Name = model.RoleName;
                role.Description = model.Description;

                var roleRuslt = isExist ? await this.roleManager.UpdateAsync(role)
                    : await this.roleManager.CreateAsync(role);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var model = new RoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                var role = this.roles.GetRoleById(id);
                if (role != null)
                {
                    model.Id = role.Id;
                    model.RoleName = role.Name;
                    model.Description = role.Description;
                }


            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, RoleViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var role = this.roles.GetRoleById(id);

                role.Name = model.RoleName;
                role.Description = model.Description;

                var roleResult = await this.roleManager.UpdateAsync(role);
                if (roleResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                this.TempData["MessageState"] = "Error";
                this.TempData["Message"] = $"Role {model.RoleName} already exists!";
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            var name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                var applicationRole = this.roles.GetRoleById(id);
                if (applicationRole != null)
                {
                    name = applicationRole.Name;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var applicationRole = this.roles.GetRoleById(id);
                if (applicationRole != null)
                {
                    var roleRuslt = this.roleManager.DeleteAsync(applicationRole).Result;
                    if (roleRuslt.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }

        #region Helpers
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                this.ModelState.AddModelError(string.Empty, error.Description);
            }
        }
        #endregion Helpers
    }
}

SoftUniAdminSystem/SUAS.Web/Areas/Administration/Controllers/UsersController.cs
namespace SUAS.Web.Areas.Administration.Controllers
{
    using System;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Services.Contracts;
    using Models;
    using ViewModels;

    [Area("Administration")]
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<Role> roleManager;
        private readonly IUserService users;
        private readonly SignInManager<ApplicationUser> signInManager;

        public UsersController(UserManager<ApplicationUser> userManager,
                               RoleManager<Role> roleManager,
                               IUserService users,
                               SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.users = users;
            this.signInManager = signInManager;
        }

        public IActionResult Index()
        {
            var allUsers = this.users.All().Select(u => new UserListViewModel
            {
                Id = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                RoleName = u.Position
            }).ToList();

            return View(allUsers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new UserViewModel
            {
                ApplicationRoles = this.roleManager.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id
                }).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.UserName,
                    Email = model.Email
                };
                var result = await this.userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    var applicationRole = await this.roleManager.FindByIdAsync(model.ApplicationRoleId);
                    if (applicationRole != null)
                    {
                        var roleResult = await this.userManager.AddToRoleAsync(user, applicationRole.Name);
                        if (roleResult.Succeeded)
                        {
                            this.TempData["MessageState"] = "Success";
                            this.TempData["Message"] = "Successfuly created user!";
                            return RedirectToAction("Index");
                        }
                    }
                }
                AddErrors(result);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var model = new EditUserViewModel
            {
                ApplicationRoles = this.roleManager.Roles.Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Id
                }).ToList()
            };

            if (!String.IsNullOrEmpty(id))
            {
                var user = await this.userManager.FindByIdAsync(id);
                if (user != null)
                {
                    model.UserName = user.UserName;
                    model.Email = user.Email;
                    model.ApplicationRoleId = this.roleManager.Roles.Single(r => r.Name == this.userManager.GetRolesAsync(user).Result.Single()).Id;
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditUserViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

                var user = await this.userManager.FindByIdAsync(id);
                if (user != null)
                {
                    user.UserName = model.UserName;
                    user.Email = model.Email;
                    var existingRole = this.userManager.GetRolesAsync(user).Result.Single();
                    var existingRoleId = this.roleManager.Roles.Single(r => r.Name == existingRole).Id;
                    var result = await this.userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        if (existingRoleId != model.ApplicationRoleId)
                        {
                            var roleResult = await this.userManager.RemoveFromRoleAsync(user, existingRole);
                            if (roleResult.Succeeded)
                            {
                                var applicationRole = await this.roleManager.FindByIdAsync(model.ApplicationRoleId);
                                if (applicationRole != null)
                                {
                                    var newRoleResult =
                                        await this.userManager.AddToRoleAsync(user, applicationRole.Name);
                                }
                            }
                        }

                        if (userId == model.Id)
                        {
                            await this.signInManager.SignOutAsync();
                            return Redirect("/Account/Login");
                        }
                        this.TempData["MessageState"] = "Success";
                        this.TempData["Message"] = "Successfuly edited user!";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrors(result);
                    }
                }
            }

            return View(id);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var name = string.Empty;
            if (!String.IsNullOrEmpty(id))
            {
                var applicationUser = await this.userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    name = applicationUser.UserName;
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var applicationUser = await this.userManager.FindByIdAsync(id);
                if (applicationUser != null)
                {
                    var result = await this.userManager.DeleteAsync(applicationUser);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return RedirectToAction("Index");
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                this.ModelState.AddModelError(string.Empty, error.Description);
            }
        }
        #endregion Helpers
    }
}

SoftUniAdminSystem/SUAS.Web/Areas/Training/Controllers/CourseController.cs
namespace SUAS.Web.Areas.Training.Controllers
{
    using System;
    using System.Linq;
    using Administration.ViewModels;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using ViewModels;

    [Area("Training")]
    public class CourseController : Controller
    {
        private readonly ICourseService courses;
        private readonly ITaskService tasks;

        public CourseController(ICourseService courses,
            ITaskService tasks)
        {
            this.courses = courses;
            this.tasks = tasks;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = this.courses.All().Select(c => new CourseListViewModel
            {
                Id = c.Id,
                Name = c.Name,
                Credits = c.Credits,
                LectureWeeks = c.LectureWeeks,
                CourseModel = c.CourseModel,
                CourseType = c.CourseType
            }).ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CourseViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    this.courses.CreateCourse(
                        model.Name,
                        model.CourseType,
                        model.CourseModel,
                        model.CapaignStartDate,
                        model.FirstLecture,
                        model.LastLecture,
                        model.ExamDate,
                        model.LectureWeeks,
                        model.ExamType,
                        model.Credits
                        );

                    return RedirectToAction("Index");
                }
                catch (ArgumentException ae)
                {
                    this.TempData["MessageState"] = "Error";
                    this.TempData["Message"] = ae.Message;
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Show(int id)
        {
            try
            {
                var course = this.courses.GetById(id);
                var tasksForCourse = this.tasks.GetAllTasksForCourse(id);

                var model = new CourseViewModel
                {
                    Id = course.Id,
                    Name = course.Name,
                    CourseType = course.CourseType,
                    CourseModel = course.CourseModel,
                    CapaignStartDate = course.CapaignStartDate,
                    FirstLecture = course.FirstLecture,
                    LastLecture = course.LastLecture,
                    ExamDate = course.ExamDate,
                    LectureWeeks = course.LectureWeeks,
                    ExamType = course.ExamType,
                    Credits = course.Credits,
                    Tasks = tasksForCourse
                };
                return View(model);
            }
            catch (ArgumentException ae)
            {
                this.TempData["MessageState"] = "Error";
                this.TempData["Message"] = ae.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

SoftUniAdminSystem/SUAS.Web/Views/Shared/Modal.cshtml
<!-- Modal -->
<div class="modal fade" id="dialog-confirm">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete</h4>
            </div>
            <div class="modal-body">
                Do you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" id="btnDelete" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('body').on('click',
            '#confirmDialog',
            function (e) {
                e.preventDefault();
                deleteLinkObj = $(this);
                $('#dialog-confirm').modal();
            });
        
        $('#btnDelete').click(function () {
            $.post(deleteLinkObj[0].href,
                function () {
                    deleteLinkObj.closest(".row").hide('fast');
                }).then(() => {
                location.reload();
            });
            $('#dialog-confirm').modal('hide');
        });
    });
</script>

SoftUniAdminSystem/SUAS.Web/Views/Shared/_AsidePartial.cshtml
@inject IUserService Users
@{
    var currentUser = Users.GetUserByUserName(User.Identity.Name);
}
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Images/ProfilePictures/@currentUser.ProfilePictureName" class="img-circle" alt="avatar">
            </div>
            <div class="pull-left info">
                <p>@currentUser.UserName</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        @*<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>*@
        @await Html.PartialAsync("_MenuPartial")
    </section>
</aside>

SoftUniAdminSystem/SUAS.Web/Views/Shared/_HeaderPartial.cshtml
@inject IUserService Users
@{
    var currentUser = Users.GetUserByUserName(User.Identity.Name);
}
<header class="main-header">
    <a asp-area="" asp-controller="Home" asp-action="Index" class="logo">
        <span class="logo-mini"><img style="width: 95%" src="~/Images/SoftUni_Logo_Small.png" alt="logo-mini" /></span>
        <span class="logo-lg"><img src="~/Images/SoftUni_Logo.png" alt="logo-lg" /></span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="~/Images/ProfilePictures/@currentUser.ProfilePictureName" class="user-image" alt="User Image">
                        <span class="hidden-xs text-black">@currentUser.UserName</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="~/Images/ProfilePictures/@currentUser.ProfilePictureName" class="img-circle" alt="User Image">
                            <p class="text-black">
                                @currentUser.UserName
                                @(currentUser.Position != null ? $"- {currentUser.Position}" : "")

                                <small>Member since @(currentUser.CreatedOn.ToString("MMM. yyyy"))</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            @*<div class="pull-left">
                                <a asp-area="" asp-action="Profile" asp-controller="Account" class="btn btn-default btn-flat">Profile</a>
                            </div>*@
                            <div class="pull-right">
                                <form asp-area="" asp-action="Logout" asp-controller="Account" method="post">
                                    <button class="btn btn-default btn-flat">Sign Out</button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

SoftUniAdminSystem/SUAS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SoftUni Admin System | @ViewData["Title"]</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <link rel="stylesheet" href="~/lib/jquery-ui/themes/blitzer/theme.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/themes/blitzer/jquery-ui.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <link href="~/dist/css/style.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @await Html.PartialAsync("_HeaderPartial")

        @await Html.PartialAsync("_AsidePartial")
        <div class="content-wrapper">
            <section class="content container-fluid">
                @{
                    var hidden = "hidden";
                    var alertType = "alert-danger";
                    if (TempData["MessageState"] != null)
                    {
                        if (TempData["MessageState"].ToString() == "Success")
                        {
                            alertType = "alert-success";
                        }
                        hidden = string.Empty;
                    }
                    
                }
                <div class="alert @alertType alert-dismissible @hidden">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> @TempData["MessageState"]!</h4>
                    @TempData["Message"]
                </div>
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                Developed by Christian Pamidoff
            </div>
            <strong>Copyright &copy; 2017 <a href="#">SoftUni Admin System</a>.</strong> All rights reserved.
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>
    <script src="~/dist/js/SidebarStateHolder.js"></script>
    <script src="~/dist/js/PreventSidebarMultipleClick.js"></script>
    <script>
        $(".alert-danger").fadeTo(2000, 500).slideUp(500, function () {
            $(".alert-danger").slideUp(500);
        });
        $(".alert-success").fadeTo(2000, 500).slideUp(500, function () {
            $(".alert-success").slideUp(500);
        });
    </script>
    @await Html.PartialAsync("Modal")
</body>
</html>

SoftUniAdminSystem/SUAS.Web/Views/Shared/_MenuPartial.cshtml
@inject UserManager<ApplicationUser> UserManager
@inject RoleManager<Role> RoleManager
@inject IUserService Users
@{
    var currentUser = Users.GetUserByUserName(User.Identity.Name);
}
<ul class="sidebar-menu" data-widget="tree">
    @if (await UserManager.IsInRoleAsync(currentUser, "Administrator"))
    {
        <li class="header">Administration</li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-link"></i> <span>Administration</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a asp-area="Administration" asp-controller="Users" asp-action="Index">Users</a></li>
                <li><a asp-area="Administration" asp-controller="Roles" asp-action="Index">Roles</a></li>
                <li><a asp-area="Administration" asp-controller="Groups" asp-action="Index">Groups</a></li>
            </ul>
        </li>

        <li class="header">Management</li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-link"></i> <span>Training</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a asp-area="Training" asp-controller="Course" asp-action="Index">Courses</a></li>
            </ul>
        </li>
    }
</ul>

SoftUniAdminSystem/SUAS.Web/Views/Shared/_UserAreaLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"]</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/plugins/iCheck/square/blue.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/plugins/iCheck/icheck.min.js"></script>
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a asp-controller="Home" asp-action="Index">
                <img src="~/Images/SoftUni_Logo.png" />
            </a>
        </div>
        @RenderBody()
        </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%'
            });
        });
    </script>
</body>
</html>