SoftUniAdminSystem/SUAS.Web/Areas/Training/ViewModels/CourseViewModel.cs
namespace SUAS.Web.Areas.Training.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    using Models;
    using Models.Enums;

    public class CourseViewModel
    {
        public int Id { get; set; }
        [Required]
        [MinLength(10)]
        [Display(Prompt = "Course Name")]
        public string Name { get; set; }
        [Required]
        public CourseType CourseType { get; set; }
        [Required]
        public CourseModel CourseModel { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{MM/dd/yyyy}")]
        public DateTime CapaignStartDate { get; set; }

        public DateTime FirstLecture { get; set; }

        public DateTime LastLecture { get; set; }

        public DateTime ExamDate { get; set; }
        [Display(Prompt = "Lecture weeks")]
        public int LectureWeeks { get; set; }

        public ExamType ExamType { get; set; }
        [Display(Prompt = "Credits")]
        [Required]
        public int Credits { get; set; }
        public List<Task> Tasks { get; set; } = new List<Task>();
    }
}

SoftUniAdminSystem/SUAS.Web/Areas/Training/Controllers/CourseController.cs
namespace SUAS.Web.Areas.Training.Controllers
{
    using System;
    using System.Linq;
    using Administration.ViewModels;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using ViewModels;

    [Area("Training")]
    public class CourseController : Controller
    {
        private readonly ICourseService courses;
        private readonly ITaskService tasks;

        public CourseController(ICourseService courses,
            ITaskService tasks)
        {
            this.courses = courses;
            this.tasks = tasks;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = this.courses.All().Select(c => new CourseListViewModel
            {
                Id = c.Id,
                Name = c.Name,
                Credits = c.Credits,
                LectureWeeks = c.LectureWeeks,
                CourseModel = c.CourseModel,
                CourseType = c.CourseType
            }).ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CourseViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    this.courses.CreateCourse(
                        model.Name,
                        model.CourseType,
                        model.CourseModel,
                        model.CapaignStartDate,
                        model.FirstLecture,
                        model.LastLecture,
                        model.ExamDate,
                        model.LectureWeeks,
                        model.ExamType,
                        model.Credits
                        );

                    return RedirectToAction("Index");
                }
                catch (ArgumentException ae)
                {
                    this.TempData["MessageState"] = "Error";
                    this.TempData["Message"] = ae.Message;
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Show(int id)
        {
            try
            {
                var course = this.courses.GetById(id);
                var tasksForCourse = this.tasks.GetAllTasksForCourse(id);

                var model = new CourseViewModel
                {
                    Id = course.Id,
                    Name = course.Name,
                    CourseType = course.CourseType,
                    CourseModel = course.CourseModel,
                    CapaignStartDate = course.CapaignStartDate,
                    FirstLecture = course.FirstLecture,
                    LastLecture = course.LastLecture,
                    ExamDate = course.ExamDate,
                    LectureWeeks = course.LectureWeeks,
                    ExamType = course.ExamType,
                    Credits = course.Credits,
                    Tasks = tasksForCourse
                };
                return View(model);
            }
            catch (ArgumentException ae)
            {
                this.TempData["MessageState"] = "Error";
                this.TempData["Message"] = ae.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

SoftUniAdminSystem/SUAS.Web/Areas/Training/Controllers/TaskController.cs
namespace SUAS.Web.Areas.Training.Controllers
{
    using System;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.Contracts;
    using ViewModels;

    [Area("Training")]
    public class TaskController : Controller
    {
        private readonly ICourseService courses;
        private readonly IGroupService groups;
        private readonly ITaskService tasks;

        public TaskController(ICourseService courses,
            IGroupService groups,
            ITaskService tasks)
        {
            this.courses = courses;
            this.groups = groups;
            this.tasks = tasks;
        }

        [HttpPost]
        public IActionResult CreateTask(int id, TaskViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                try
                {
                    var course = this.courses.GetById(id);
                    var group = this.groups.GetByName(model.ResponsibleGroupName);

                    var isCreated = this.tasks.CreateTask(group, model.Process, model.DueDate, course);

                    if (isCreated)
                    {
                        this.TempData["MessageState"] = "Success";
                        this.TempData["Message"] = "Successfully created new task!";
                    }
                }
                catch (ArgumentException ae)
                {
                    this.TempData["MessageState"] = "Error";
                    this.TempData["Message"] = ae.Message;
                }
            }

            return RedirectToAction("Show", "Course", new { id });
        }

        [HttpGet]
        public IActionResult CompleteTask(int id)
        {
            var task = this.tasks.GetById(id);
            if (task != null)
            {
                try
                {
                    var isCompleted = this.tasks.CompleteTask(task);

                    if (isCompleted)
                    {
                        this.TempData["MessageState"] = "Success";
                        this.TempData["Message"] = "Successfully completed task!";
                    }
                }
                catch (ArgumentException ae)
                {
                    this.TempData["MessageState"] = "Error";
                    this.TempData["Message"] = ae.Message;
                }
            }


            return RedirectToAction("Show", "Course", new { id = task.CourseId });
        }
    }
}

SoftUniAdminSystem/SUAS.Web/Areas/Training/Views/Course/Create.cshtml
@using SUAS.Web.Areas.Training.ViewModels
@using SUAS.Models.Enums
@model CourseViewModel

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Course</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form asp-controller="Course" asp-action="Create" method="post" class="form-horizontal">
            <div class="box-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="Name" class="form-control" required="required">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="CourseType" class="col-sm-2 control-label"></label>
                    <div class="col-sm-10">
                        <select asp-for="CourseType" asp-items="Html.GetEnumSelectList<CourseType>()" class="form-control" required="required">
                            <option value="">Please select</option>
                        </select>
                        <span asp-validation-for="CourseType" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="CourseModel" class="col-sm-2 control-label"></label>
                    <div class="col-sm-10">
                        <select asp-for="CourseModel" asp-items="Html.GetEnumSelectList<CourseModel>()" class="form-control" required="required">
                            <option value="">Please select</option>
                        </select>
                        <span asp-validation-for="CourseModel" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="CapaignStartDate" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="CapaignStartDate" class="form-control" required="required" type="date">
                        <span asp-validation-for="CapaignStartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="FirstLecture" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="FirstLecture" class="form-control" required="required" type="date">
                        <span asp-validation-for="FirstLecture" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="LastLecture" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="LastLecture" class="form-control" required="required" type="date">
                        <span asp-validation-for="LastLecture" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ExamDate" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="ExamDate" class="form-control" required="required" type="date">
                        <span asp-validation-for="ExamDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="LectureWeeks" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="LectureWeeks" class="form-control" required="required">
                        <span asp-validation-for="LectureWeeks" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ExamType" class="col-sm-2 control-label"></label>
                    <div class="col-sm-10">
                        <select asp-for="ExamType" asp-items="Html.GetEnumSelectList<ExamType>()" class="form-control" required="required">
                            <option value="">Please select</option>
                        </select>
                        <span asp-validation-for="ExamType" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Credits" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input asp-for="Credits" class="form-control" required="required">
                        <span asp-validation-for="Credits" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <a asp-controller="Course" asp-action="Index" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-info pull-right">Create</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
</section>

SoftUniAdminSystem/SUAS.Web/Areas/Training/Views/Course/Index.cshtml
@using SUAS.Web.Areas.Training.ViewModels
@model IEnumerable<CourseListViewModel>

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Courses</h3>
    </div>
    <div class="box-body table-responsive no-padding">
        <a asp-controller="Course" asp-action="Create" class="btn bg-olive margin text-center">
            Add Course
        </a>
        <table class="table table-hover">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>Course Name</th>
                    <th>Credits</th>
                    <th>Lecture weeks</th>
                    <th>Course model</th>
                    <th>Course type</th>
                </tr>
                @foreach (var course in Model)
                {
                    <tr>
                        <td>@course.Id</td>
                        <td><a asp-area="Training" asp-controller="Course" asp-action="Show" asp-route-id="@course.Id">@course.Name</a></td>
                        <td>@course.Credits</td>
                        <td>@course.LectureWeeks</td>
                        <td>@course.CourseModel</td>
                        <td>@course.CourseType</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SoftUniAdminSystem/SUAS.Web/Areas/Training/Views/Course/Show.cshtml
@model SUAS.Web.Areas.Training.ViewModels.CourseViewModel

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header text-center">
                <h2 class="box-title">@Model.Name</h2>
                <p>Course type: @Model.CourseType</p>
                <p>Course model: @Model.CourseModel</p>
                <p>Start: @Model.FirstLecture.ToShortDateString() -  End: @Model.LastLecture.ToShortDateString()</p>
                <p>Exam: @Model.ExamType - @Model.ExamDate.ToShortDateString()</p>
                <p>Credits: @Model.Credits</p>
            </div>
            <div class="box-body table-responsive">
                <table class="table table-hover tasks">
                    <tbody>
                        <tr>
                            <th>Responsible</th>
                            <th>Process</th>
                            <th>Due date</th>
                            <th>Completed</th>
                        </tr>
                        @foreach (var task in Model.Tasks)
                        {
                            <tr class="task-info">
                                <td><a asp-area="Administration" asp-controller="Groups" asp-action="Show" asp-route-id=@task.Id></a>@task.ResponsibleGroup.Name</td>
                                <td>@task.Process</td>
                                <td>@task.DueDate.ToShortDateString()</td>
                                <td>
                                    @if (task.Completed)
                                    {<i class="fa fa-check" aria-hidden="true"></i> }
                                    else
                                    { <i class="fa fa-times" aria-hidden="true"></i>}
                                </td>
                                <td>
                                    @if (!task.Completed)
                                    {
                                        <a class="btn btn-success" asp-area="Training" asp-controller="Task" asp-action="CompleteTask" asp-route-id=@task.Id>Complete</a>
                                    }
                                    else
                                    {
                                        <span>Completed on @task.CompletedOn.ToShortDateString()</span>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <button class="btn btn-primary" id="btnAddTask">Add</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#btnAddTask").click(function() {
            var btnText = $('#btnAddTask').text();
            if (btnText == 'Close') {
                $(".task-info").last().remove();
                $('#btnAddTask').text('Add');
            } else {
                $(".tasks tbody").append(
                    $('<tr>').addClass('task-info')
                    .append(
                        $('<form>').attr('method', 'post').attr('action', '/Training/Task/CreateTask?id=' + @Model.Id)
                        .append(
                            $('<td>')
                            .append(
                            $('<input>').addClass('tasks-auto').attr('name', 'ResponsibleGroupName').attr('type', 'text').attr('autofocus', 'autofocus').attr('placeholder', 'Group name')
                        ),
                        $('<td>')
                            .append(
                                $('<input>').addClass('process').attr('name', 'Process').attr('type', 'text').attr('placeholder', 'Process')
                            ),
                            $('<td>')
                            .append(
                                $('<input>').addClass('dueDate').attr('name', 'DueDate').attr('type', 'date').attr('placeholder', 'Due date')
                            ),
                            $('<td>')
                            .append(
                                $('<input>').addClass('btn btn-success').attr('type', 'submit').attr('value', 'save')
                            )
                        )
                    )
                );
                $("#btnAddTask").text('Close');
            }
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#btnAddTask").click(function () {
            $(() => {
                var availableUsernames = [];
                $.ajax({
                    type: 'GET',
                    url: '/Administration/Groups/GetAllGroups/',
                    success: (result) => {
                        availableUsernames = result;
                        $(".tasks-auto").autocomplete({
                            source: availableUsernames
                        });
                    },
                    error: (result) => {
                        console.log(result);
                    }
                });
            });
        });
    });
</script>